# 通用的配置
# author : ChenYingxiang
server:
  port: 8001

config:
  info: 嗨嗨嗨-dev

# mybatis配置相关的
mybatis:
  # mapper文件哪里找
  mapper-locations: classpath*:/mybatis/**/*.xml
  # 类型别名指定的基本的包
  type-aliases-package: com.lucky.springcloud.entities
  # 配置日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


eureka:
  instance:
    instance-id: payment8001 # 配置主机名称
    prefer-ip-address: true
      #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
    lease-renewal-interval-in-seconds: 30
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
    lease-expiration-duration-in-seconds: 90
  client:
    #表示是否将自己注册进EurekaServer默认为true。服务提供者，所以肯定需要注册
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url: # 注册中心的地址
      defaultZone: http://eureka7001.com:7001/eureka


spring:
  application:
    name: cloud-payment-service
  # 数据源连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springclouddb?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: chen18

  mvc:
    # 内容协商，自定义浏览器接收类型，通过参数format
    contentnegotiation:
      favor-parameter: true

    # 开启请求体的，方法类型解析
    hiddenmethod:
      filter:
        enabled: true

  # 设置上传文件大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB




